title: 🥇 David Azcona's site
url: "https://computing.dcu.ie/~dazcona/"

author: David Azcona
author_title: Applied Scientist
email: david.azcona@zalando.ie
author_dcu: Postdoctoral Researcher
email_dcu: david.azcona@dcu.ie
author_fulbright: Fulbright Visiting scholar
email_fulbright: david.azcona@asu.edu
department: School of Computing
department_url: https://computing.dcu.ie
research_centre: Insight Centre for Data Analytics
research_centre_url: https://insight-centre.org
company: Zalando
company_url: https://en.zalando.de/
university: Dublin City University
university_url: https://dcu.ie
university_usa: Arizona State University
university_usa_url: https://asu.edu

blog_title: 'My Blog'

baseurl:
pubs_path: /pubs
permalink: /:categories/:title
navigation:
    - title: Home
      link: /
    - title: Blog
      link: /blog
    - title: Publications
      link: /publications.html
    - title: CV
      link: /cv.html
    - title: Awards
      link: /awards.html
    - title: Media
      link: /media.html

ga_id: UA-110743398-1
ga_domain: dcu.ie

highlighter: true
markdown: kramdown
# kramdown:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

scholar:
  style: apa-no-doi-no-issue
  locale: en

  sort_by: year, month
  order: descending

  repository: ./pubs
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }} {% if links.pdf %}<a href=\"{{ links.pdf }}\">PDF</a> {% endif %} "

  replace_strings: true
  join_strings:    true

  details_dir:    bibtex
  details_layout: bibtex.html
  details_link: BibTeX

  query: "@*"